on: 
  push:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Create namespace
      uses: okteto/create-namespace@master
      with:
        namespace: pr-${{ github.event.number }}-mnevadom

    - name: Deploy Application
      uses: okteto/pipeline@master
      with:
        namespace: pr-${{ github.event.number }}-mnevadom
        name: pr-${{ github.event.number }}
        timeout: 10m

    - name: comment PR
      uses: okteto/notify-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: "Preview environment available at https://movies-pr-${{ github.event.number }}-cindylopez.cloud.okteto.net"
